# Generated by Django 6.0.4 on 2026-05-06 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_student_id_alter_feedback_date_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='date_assigned',
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily Goal'), ('weekly', 'Weekly Goal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='backendapp.student'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_goals', to='backendapp.supervisor'),
        ),
    ]
