# Generated by Django 6.0.5 on 2026-05-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_alter_report_status_goalfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_used',
            new_name='is_verified',
        ),
    ]
