# Generated by Django 6.0.5 on 2026-05-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_rename_is_used_otp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
